name: GCP Auth with OIDC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  authenticate:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account_email: cis410-deploy-sa@cis410-langombo-498119.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Test GCP authentication
        run: |
          gcloud auth list
          gcloud config list
          gcloud projects list
